apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    app: web
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: key-value-store
          image: redis
          ports:
            - containerPort: 6379
