apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    product: kafka

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 2
  template:
    metadata:
      labels:
        product: kafka
    spec:
      containers:
        - name: kafka
          image: evonove/kafka:k8s
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ZOOKEEPER_CONNECT
              value: zoo-0.zoo.$(NAMESPACE).svc.cluster.local:2181,zoo-1.zoo.$(NAMESPACE).svc.cluster.local:2181,zoo-2.zoo.$(NAMESPACE).svc.cluster.local:2181
          volumeMounts:
            - name: datadir
              mountPath: /opt/kafka/data
      volumes:
        - name: datadir
          emptyDir: {}

