apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    product: kafka

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-controller
spec:
  serviceName: "kafka-service"
  replicas: 2
  template:
    metadata:
      labels:
        product: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #  value: "kafka-controller-0"
        - name: HOSTNAME_COMMAND
          # value: "wget -t3 -T2 -qO-  http://169.254.169.254/latest/meta-data/local-ipv4"
          value: "hostname"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo-0.zoo.tutorial.svc.cluster.local:2181,zoo-1.zoo.tutorial.svc.cluster.local:2181,zoo-2.zoo.tutorial.svc.cluster.local:2181
        - name: KAFKA_CREATE_TOPICS
          value: logstashlogs:1:1
        volumeMounts:
          - name: datadir
            mountPath: /kafka
      volumes:
        - name: datadir
          emptyDir: {}

